service: finance-push
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  financePush:
    handler: handler.financePush
    events:
      - schedule: cron(0 23 * * ? *)
    environment: ${file(env.yml)}
